### ISSUE TITLE
'mouseenter' and 'mouseleave' events are triggered in unexpected area of custom displayobject

### ISSUE THREAD

**Issue by discopatrick** [koggdal/ocanvas#107]
I have created a custom displayobject using oCanvas.registerDisplayObject

However, when binding a "mouseenter" event to an instance of this displayobject, the event does not get triggered when I move the mouse over the shape itself. In fact, it is triggered when I move the mouse over a specific area outside the shape.

This can be best explained by my example here: https://jsfiddle.net/discopatrick/o56qeh22/

Is this a limitation/bug of the library, or have I not created/closed my path correctly?

**Comment by koggdal** [comment]
oCanvas does unfortunately not support mouse events for arbitrary shapes, only the ones provided in oCanvas itself. For custom objects, it will make a best guess based on the `shapeType` (which can be `rectangular` or `radial`). For `radial` it will assume the x/y position of the object is at the center and create a circular hit area around that point, which is why you see it happening slightly offset from the shape you've drawn.
