### ISSUE TITLE
oCanvas click stop work in chrome 45.0.2454.101 m

### ISSUE THREAD

**Issue by shifugate** [koggdal/ocanvas#118]
oCanvas click stop work in chrome 45.0.2454.101 m.

**Comment by koggdal** [comment]
Does your computer have a touch display? If so, that's how it is for now unfortunately. The current version of oCanvas was built before touch laptops were this popular, and detects if touch is available. If it is, it starts listening for touch events only. If it is not, it starts listening for mouse events only. Computers with both are currently not handled, sorry. I started on a new major version of oCanvas, including a much improved event system supporting both input devices, but due to lack of time I haven't been able to finish it yet, and it won't be in the near future either. Again, sorry about that.

If the problem is not touch related, could you give me more details? I'm running Chrome 46 on a MacBook 2015 and it works fine for me. Could you also check what this evaluates to in your Chrome dev console?

```js
"ontouchstart" in window || "createTouch" in document
```

**Comment by shifugate** [comment]
Hi, thanks for response and sorry for my english.
The chrome console warning is: 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.
Test demo link: http://ocanvas.org/demos/2
SO: Windows 10.
Chrome version: 45.0.2454.101 m

**Comment by koggdal** [comment]
That warning is unrelated to the problem you're describing.

Could you answer my other questions? Thanks.

**Comment by mgriffel** [comment]
Hello,

I have the same problem with Chrome version 52.0.2743.116 and Windows 10. 

The expression `"ontouchstart" in window || "createTouch" in document` returns `true` on the Chrome console .

When I set the chrome setting 'Enable touch events' from 'Automatic' to 'Disabled'  in 'chrome://flags/' everything works fine (`"ontouchstart" in window || "createTouch" in document` returns `false`).

**Comment by Canopee** [comment]
Bonjour,

Actuellement en congés, je prendrai connaissance de votre message à mon retour le mardi 23 août 2016.

Je vous souhaite une bonne période estivale.

Cordialement,

Coline Ducasse

**Comment by koggdal** [comment]
Thanks @mgriffel. Unfortunately that's how it is for now, there will be no fix in the near future due to lack of time. Sorry about that.
