### ISSUE TITLE
Flickering issue - possible bug in reinitialization of canvas

### ISSUE THREAD

**Issue by Kenterfie** [koggdal/ocanvas#129]
I've found a problem, when i try to reinitialize a canvas and try to destroy the old context the canvas starts flickering.

Workaround
I remove the current dom canvas element and create a new one

Sample
https://jsfiddle.net/Kenterfie/ombh8njf/
In this sample i create a canvas two times. In some cases the flickering starts immediately, if not try to drag one of the circles.

I have tried different methods to fix the issue, but all without success
* delete canvas object
* use destroy/clear/reset methods of ocanvas
* set to null

Does someone knows the correct way to reinitialize a canvas mutliple times.

**Comment by koggdal** [comment]
Thanks for reporting the issue!

The problem seems to be that `destroy` is not cancelling the timeline, so that keeps running and redraws each frame. I'll fix it! In the meantime you should be able to work around it by calling `canvas.timeline.stop()` before calling `canvas.destroy()`.

I also saw in the code sample that there's confusion around `setLoop`. That is due to how rendering works in oCanvas. You change properties of objects and then you call `canvas.redraw()` to update the rendering. But when using the timeline to update things each frame, the call to redraw is automatic. If all you need is to redraw after a mouse event and you don't need updates each frame, you can just call `canvas.redraw()` in the event handler.

**Comment by koggdal** [comment]
Fixed the issue in 2.8.6: http://ocanvas.org/download#v2.8.6

Thanks again for reporting and providing a great test case! :+1:
